[package]
name = "zac134/better-config"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = []

[dependencies]
signal = "sleitnick/signal@2.0.3"
