[package]
name = "zac134/rbx-config"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["Packages", "README.md"]
authors = ["yaSu <https://github.com/Zac134>"]
description = "Roblox ConfigService Wrapper"

[dependencies]
signal = "sleitnick/signal@^2.0"
